config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = %w(chinese italian japanese french belgian)
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :phone_number, presence: true
  validates :category, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: %i[show]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:create]
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Butcher</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="http://localhost:3000/restaurants">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Restaurants</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Category</a>
      </li>
    </ul>
    <span class="navbar-text">
      Create Restaurant
    </span>
  </div>
</nav>


<div class="container">
<h1 class="nnavbar navbar-expand-lg navbar-light bg-light">My list of restaurants</h1>
  <div class="row">
    <div class="col-12">
      <% @restaurants.each do |restaurant| %>
      <div class="card ">
        <h2 class="card-header btn btn-success"><%=link_to restaurant.name, restaurant_path(restaurant), class: "text" %></h2>
        <p class="card-title"><%= restaurant.address %></p>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>Add a Restaurant here.</h1>

        <%= simple_form_for @restaurant do |f| %>
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :phone_number %>
          <%= f.input :category, collection: Restaurant::CATEGORY %>
          <%= f.submit "Add a restaurant", class: "btn btn-primary" %>
        <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="http://localhost:3000/restaurants">Butcher</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="http://localhost:3000/restaurants">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://localhost:3000/restaurants">Restaurants</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Category</a>
      </li>
    </ul>
    <span class="navbar-text">
      Create Restaurant
    </span>
  </div>
</nav>
<h1 class="navbar-nav"><%= @restaurant.name %></h1>
<div class="container">
  <div class="row">
    <div class="col-12">
      <li><h3>Location:</h3> <h4><%= @restaurant.address %></h4></li>
      <li><h3>Phone Number:</h3> <h4><%= @restaurant.phone_number %></h4></li>
      <li><h3>Category:</h3> <h4><%= @restaurant.category %></h4></li>
      <% @restaurant.reviews.each do |review| %>
       <h2> Review: <br><%= review.content %> <%= review.rating %> </h2>
      <% end %>
      <%= link_to "home", restaurants_path %>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>